/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IconBx:BxlFacebookCircle': typeof import('~icons/bx/bxl-facebook-circle')['default']
    'IconBx:BxlGithub': typeof import('~icons/bx/bxl-github')['default']
    'IconBx:BxlLinkedin': typeof import('~icons/bx/bxl-linkedin')['default']
    'IconBx:BxlTwitter': typeof import('~icons/bx/bxl-twitter')['default']
    'IconBx:BxlYoutube': typeof import('~icons/bx/bxl-youtube')['default']
    'IconBx:BxsLeaf': typeof import('~icons/bx/bxs-leaf')['default']
    'IconMaterialSymbols:CalendarToday': typeof import('~icons/material-symbols/calendar-today')['default']
    'IconMaterialSymbols:CheckCircle': typeof import('~icons/material-symbols/check-circle')['default']
    'IconMaterialSymbols:MenuRounded': typeof import('~icons/material-symbols/menu-rounded')['default']
    'IconMaterialSymbols:NestClockFarsightAnalogRounded': typeof import('~icons/material-symbols/nest-clock-farsight-analog-rounded')['default']
    'IconMaterialSymbols:PlayCircle': typeof import('~icons/material-symbols/play-circle')['default']
    'IconMdi:CloseCircle': typeof import('~icons/mdi/close-circle')['default']
    'IconMdi:InformationVariantCircle': typeof import('~icons/mdi/information-variant-circle')['default']
    'IconOcticon:TriangleDown16': typeof import('~icons/octicon/triangle-down16')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
